### ISSUE TITLE
ValueError: Empty training data.

### ISSUE THREAD

**Issue by xji-apex** [vseasky/yolo-for-k210#1]
你好，自定义数据集（401张图片），报错：ValueError:Empty training data.修改过dataset里的shuffle参数，仍然报该错误，可以给指点一下嘛？
  1/190 [..............................] - ETA: 21:51 - loss: 897.8262 - l1_loss: 169.9690 - l2_loss: 727.4587 - l1_p: 0.0769 - l1_r: 0.6667 - l2_p: 0.0000e+00 - l2_r: 0.0000e+002020-09-16 12:46:54.344528: I tensorflow/core/profiler/lib/profiler_session.cc:205] Profiler session started.
2020-09-16 12:46:54.349900: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cupti64_100.dll'; dlerror: cupti64_100.dll not found
2020-09-16 12:46:54.354959: W tensorflow/core/profiler/lib/profiler_session.cc:213] Encountered error while starting profiler: Unavailable: CUPTI error: CUPTI could not be loaded or symbol could not be found.
  2/190 [..............................] - ETA: 11:03 - loss: 961.8444 - l1_loss: 242.9070 - l2_loss: 718.5386 - l1_p: 0.0663 - l1_r: 0.4286 - l2_p: 0.0000e+00 - l2_r: 0.0000e+002020-09-16 12:46:54.576991: I tensorflow/core/platform/default/device_tracer.cc:588] Collecting 0 kernel records, 0 memcpy records.
2020-09-16 12:46:54.583706: E tensorflow/core/platform/default/device_tracer.cc:70] CUPTI error: CUPTI could not be loaded or symbol could not be found.
189/190 [============================>.] - ETA: 0s - loss: 157.4149 - l1_loss: 80.9354 - l2_loss: 76.0476 - l1_p: 0.0444 - l1_r: 0.0053 - l2_p: 0.0000e+00 - l2_r: 0.0000e+00Traceback (most recent call last):
  File "./keras_train.py", line 155, in <module>
    args.prune_frequency)
  File "./keras_train.py", line 99, in main
    validation_data=h.test_dataset, validation_steps=int(h.test_epoch_step * h.validation_split))
  File "D:\Anaconda\envs\seayolok210\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 727, in fit
    use_multiprocessing=use_multiprocessing)
  File "D:\Anaconda\envs\seayolok210\lib\site-packages\tensorflow_core\python\keras\engine\training_arrays.py", line 675, in fit
    steps_name='steps_per_epoch')
  File "D:\Anaconda\envs\seayolok210\lib\site-packages\tensorflow_core\python\keras\engine\training_arrays.py", line 440, in model_iteration
    steps_name='validation_steps')
  File "D:\Anaconda\envs\seayolok210\lib\site-packages\tensorflow_core\python\keras\engine\training_arrays.py", line 411, in model_iteration
    aggregator.finalize()
  File "D:\Anaconda\envs\seayolok210\lib\site-packages\tensorflow_core\python\keras\engine\training_utils.py", line 138, in finalize
    raise ValueError('Empty training data.')
**ValueError: Empty training data.
mingw32-make: *** [Makefile:35: train] Error 1**

**Comment by noobgrow** [comment]
> 你好，自定义数据集（401张图片），报错：ValueError:Empty training data.修改过dataset里的shuffle参数，仍然报该错误，可以给指点一下嘛？
> 1/190 [..............................] - ETA: 21:51 - loss: 897.8262 - l1_loss: 169.9690 - l2_loss: 727.4587 - l1_p: 0.0769 - l1_r: 0.6667 - l2_p: 0.0000e+00 - l2_r: 0.0000e+002020-09-16 12:46:54.344528: I tensorflow/core/profiler/lib/profiler_session.cc:205] Profiler session started.
> 2020-09-16 12:46:54.349900: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cupti64_100.dll'; dlerror: cupti64_100.dll not found
> 2020-09-16 12:46:54.354959: W tensorflow/core/profiler/lib/profiler_session.cc:213] Encountered error while starting profiler: Unavailable: CUPTI error: CUPTI could not be loaded or symbol could not be found.
> 2/190 [..............................] - ETA: 11:03 - loss: 961.8444 - l1_loss: 242.9070 - l2_loss: 718.5386 - l1_p: 0.0663 - l1_r: 0.4286 - l2_p: 0.0000e+00 - l2_r: 0.0000e+002020-09-16 12:46:54.576991: I tensorflow/core/platform/default/device_tracer.cc:588] Collecting 0 kernel records, 0 memcpy records.
> 2020-09-16 12:46:54.583706: E tensorflow/core/platform/default/device_tracer.cc:70] CUPTI error: CUPTI could not be loaded or symbol could not be found.
> 189/190 [============================>.] - ETA: 0s - loss: 157.4149 - l1_loss: 80.9354 - l2_loss: 76.0476 - l1_p: 0.0444 - l1_r: 0.0053 - l2_p: 0.0000e+00 - l2_r: 0.0000e+00Traceback (most recent call last):
> File "./keras_train.py", line 155, in
> args.prune_frequency)
> File "./keras_train.py", line 99, in main
> validation_data=h.test_dataset, validation_steps=int(h.test_epoch_step * h.validation_split))
> File "D:\Anaconda\envs\seayolok210\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 727, in fit
> use_multiprocessing=use_multiprocessing)
> File "D:\Anaconda\envs\seayolok210\lib\site-packages\tensorflow_core\python\keras\engine\training_arrays.py", line 675, in fit
> steps_name='steps_per_epoch')
> File "D:\Anaconda\envs\seayolok210\lib\site-packages\tensorflow_core\python\keras\engine\training_arrays.py", line 440, in model_iteration
> steps_name='validation_steps')
> File "D:\Anaconda\envs\seayolok210\lib\site-packages\tensorflow_core\python\keras\engine\training_arrays.py", line 411, in model_iteration
> aggregator.finalize()
> File "D:\Anaconda\envs\seayolok210\lib\site-packages\tensorflow_core\python\keras\engine\training_utils.py", line 138, in finalize
> raise ValueError('Empty training data.')
> **ValueError: Empty training data. mingw32-make: *** [Makefile:35: train] Error 1**

请问您解决了吗

**Comment by samwang90** [comment]
遇到同样的问题

**Comment by noobgrow** [comment]
> 遇到同样的问题

https://github.com/zhen8838/K210_Yolo_framework/issues/26
我把训练集增加到20000+就好了。。

**Comment by zhiyuan1i** [comment]
> > 遇到同样的问题
> 
> [zhen8838/K210_Yolo_framework#26](https://github.com/zhen8838/K210_Yolo_framework/issues/26)
> 我把训练集增加到20000+就好了。。

但是小数据集没有办法增加呀……，错误在每个epoch后出现，应该是val数据集的量不够。

**Comment by SHZHYE** [comment]
> > > 遇到同样的问题
> > 
> > 
> > [zhen8838/K210_Yolo_framework#26](https://github.com/zhen8838/K210_Yolo_framework/issues/26)
> > 我把训练集增加到20000+就好了。。
> 
> 但是小数据集没有办法增加呀……，错误在每个epoch后出现，应该是val数据集的量不够。

请问你解决了嘛，我也是这个问题，数据集自己制作的（三百多个），再增加上万张感觉不太现实啊

**Comment by zhiyuan1i** [comment]
> > > > 遇到同样的问题
> > > 
> > > 
> > > [zhen8838/K210_Yolo_framework#26](https://github.com/zhen8838/K210_Yolo_framework/issues/26)
> > > 我把训练集增加到20000+就好了。。
> > 
> > 
> > 但是小数据集没有办法增加呀……，错误在每个epoch后出现，应该是val数据集的量不够。
> 
> 请问你解决了嘛，我也是这个问题，数据集自己制作的（三百多个），再增加上万张感觉不太现实啊

解决了，查看MakeFile，make指定BATCH=8 SPLITFACTOR=0.3，您可以稍微调整后面的参数
SPLITFACTOR 指定了自动生成测试数据集的样本数量，可以适量调大。
